# **UTS Modeling** 

In [3]:
!pip install numpy
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np
import pandas as pd

## Load Preproced data

In [5]:
data = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/data-pta-cleaned.csv",index_col=0)
data.head()

NPM                                              Judul  \
0  40411100468  perancangan dan implementasi sistem database t...   
1  40411100476  aplikasi kontrol dan monitoring jaringan kompu...   
2  40411100480  rancang bangun aplikasi proxy server untukenkr...   
3  70411100070  sistem pendukung keputusan optimasi penjadwala...   
4  80411100115  sistem augmented reality animasi benda bergera...   

                                             Abstrak               Prodi  \
0  sistem informasi akademik siakad merupakan sis...  Teknik Informatika   
1  berjalannya koneksi jaringan komputer dengan l...  Teknik Informatika   
2  web server adalah sebuah perangkat lunak serve...  Teknik Informatika   
3  penjadwalan kuliah di perguruan tinggi merupak...  Teknik Informatika   
4  seiring perkembangan teknologi yang ada diduni...  Teknik Informatika   

       Label                                       judul_tokens  \
0        RPL  ancangimplementasisistemdatabasedistribusiorac...   
1        RPL   aplikasikontrolmonitoringjaringkomputerbasmobile   
2        RPL  rancangbangunaplikasiproxyserveruntukenkripsik...   
3  komputasi  sistemdukungputusoptimasijadwalmatakuliahgunar...   
4  komputasi  sistemaugmentedrealityanimasibendagerakflartoo...   

                                      abstrak_tokens  
0  sisteminformasiakademiksiakadsisteminformasifu...  
1  jalankoneksijaringkomputerlancargangguharappen...  
2  webserverperangkatlunakserverberfungsimenerima...  
3  jadwalkuliahgurukompleksmasalahvariabeltimbang...  
4  iringkembangteknologiduniamunculteknologiaugme...

### Split Data

In [6]:
from sklearn.model_selection import train_test_split

X = data['abstrak_tokens']
y = data['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Feature Extration: TF-IDF

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
countvectorizer = CountVectorizer()
tfidfvectorizer = TfidfVectorizer()

count_wm = countvectorizer.fit_transform(X)
tfidf_wm = tfidfvectorizer.fit_transform(X)

In [8]:
count_tokens = countvectorizer.get_feature_names_out()
tfidf_tokens = tfidfvectorizer.get_feature_names_out()
df_countvect = pd.DataFrame(data = count_wm.toarray(),columns = count_tokens)
df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),columns = tfidf_tokens)
print("Count Vectorizer\n")
df_countvect

Count Vectorizer



abstractjagungkabupatenpamekasanmakanpokokgantiberassediajagungcukupbutuhbutuhsistemmenganalisatujutelitisediajagungalternatifbijaktingkatsediajagungmetodetelitidekatsistemdinamiklanjutsimulasidasarskenariotetapaspekkajitelitiliputsubsistemsediasubsistembutuhmodelsistemdinamikalatbantudiagramsimpalkausalloopshasilstrukturmodeldinamisperilakusistemdinamisdasarhasilsimulasitingkatsediajagungpamekasantingkatproduksijagunggunapupuknpkgunabibitunggulhibridagabunggunapupuknpktingkatproduksijagunggunabibitunggulhibridatingkatproduksijagunggunabibithibridapupuknpktingkatproduksijagung  \
0                                                    0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
1                                                    0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
2                                                    0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
3                                                    0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
4                                                    0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
..                                                 ...                                                                                                                                                                                                                                                                                                                                                                                                               

PCA

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
A=scaler.fit(df_countvect)

In [17]:
scaled_data=scaler.transform(df_countvect)
scaled_data

array([[-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988],
       [-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988],
       [-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988],
       ...,
       [-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988],
       [-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988],
       [-0.03517988, -0.03517988, -0.03517988, ..., -0.03517988,
        -0.03517988, -0.03517988]])

In [18]:
tfidf_wm.shape

(809, 809)

In [19]:
# Impor library yang dibutuhkan
from sklearn.decomposition import PCA

# Inisialisasi objek PCA dengan 3 komponen
pca = PCA(n_components=3)

# Melakukan fit transform pada data
X_pca = pca.fit_transform(tfidf_wm.toarray())

In [11]:
X_pca.shape

(809, 3)

In [20]:
num_components=2

pca=PCA(num_components)
pca.fit(scaled_data)
PCA(copy=True, iterated_power="auto",n_components=num_components, random_state=None, svd_solver="auto",tol=0.0, whiten=False)


PCA(n_components=2)

In [21]:
pca.explained_variance_

array([1.00247678, 1.00247678])

In [22]:
pca.explained_variance_ratio_

array([0.00123762, 0.00123762])

In [24]:
pca.components_

array([[-0.03074511, -0.0006416 , -0.05561979, ..., -0.02024039,
        -0.01403361,  0.03950487],
       [-0.0338501 , -0.03492163, -0.03243726, ..., -0.02604362,
         0.01033664, -0.00854572]])

### Split Data

In [32]:
from sklearn.model_selection import train_test_split
training, test = train_test_split(X_pca,test_size=0.2, random_state=1)#Nilai X training dan Nilai X testing
training_label, test_label = train_test_split(y, test_size=0.2, random_state=1)#Nilai Y training dan Nilai Y testing

#### KNN

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

modelKNN = KNeighborsClassifier(n_neighbors=5)
modelKNN.fit(training, training_label)

KNeighborsClassifier()

In [34]:
test_pred = modelKNN.predict(test)
test_pred

array(['komputasi', 'komputasi', 'komputasi', 'komputasi', 'PBA',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'RPL', 'RPL', 'RPL', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
   

In [35]:
accuracy_score(test_label, test_pred)

0.6111111111111112

In [36]:
print(classification_report(test_label, test_pred))

              precision    recall  f1-score   support

         PBA       0.00      0.00      0.00        10
         RPL       0.00      0.00      0.00        41
   komputasi       0.66      0.89      0.76       111

    accuracy                           0.61       162
   macro avg       0.22      0.30      0.25       162
weighted avg       0.46      0.61      0.52       162



#### Naive Baiyes

In [37]:
#Model Select
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(training, training_label)

GaussianNB()

In [38]:
predict = gaussian.predict(test) 
predict

array(['komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komputasi',
       'komputasi', 'komputasi', 'komputasi', 'komputasi', 'komp

In [39]:
accuracy_score(test_label, predict)

0.6851851851851852

In [40]:
print(classification_report(test_label, predict))

              precision    recall  f1-score   support

         PBA       0.00      0.00      0.00        10
         RPL       0.00      0.00      0.00        41
   komputasi       0.69      1.00      0.81       111

    accuracy                           0.69       162
   macro avg       0.23      0.33      0.27       162
weighted avg       0.47      0.69      0.56       162



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
